import { StyleSheet } from 'react-native';

import { prototypeColors as colors, prototypeTypography as type } from './prototypeStyles';

export const leagueTypography = StyleSheet.create({
  title: type.planHeading,
  heading: type.compactPageHeading,
  name: type.compactCardTitle,
  caption: type.caption,
  selectedTab: type.compactCardTitle,
  tab: { ...type.compactAction, fontSize: 15, color: colors.muted },
  rank: {
    ...type.caption,
    fontFamily: 'Inter_600SemiBold',
    color: colors.subtle,
    textAlign: 'center',
  },
  myRank: { ...type.caption, fontFamily: 'Inter_700Bold', color: colors.ink, textAlign: 'center' },
  score: type.compactCardTitle,
  myScore: { ...type.compactCardTitle, fontFamily: 'Inter_700Bold', color: colors.accent },
  badge: { ...type.badge, color: '#fff', textAlign: 'center' },
  body: type.body,
});
export const leagueStyles = StyleSheet.create({
  header: { paddingHorizontal: 22, paddingTop: 8 },
  period: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  tabs: {
    marginTop: 18,
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  tab: {
    flex: 1,
    minHeight: 44,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    marginBottom: -1,
  },
  podium: {
    marginHorizontal: 22,
    marginTop: 24,
    paddingBottom: 4,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  row: {
    marginHorizontal: 22,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
  },
  me: {
    marginHorizontal: 22,
    marginTop: 16,
    marginBottom: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    shadowColor: '#1e140a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 3,
  },
  rank: { minWidth: 18, flexShrink: 0 },
  progress: {
    marginTop: 8,
    height: 4,
    borderRadius: 2,
    overflow: 'hidden',
    backgroundColor: '#f0f0f0',
  },
  metric: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 5, flexShrink: 1 },
  footer: { marginHorizontal: 22, marginTop: 28, paddingBottom: 28 },
});
