import { StyleSheet, TextStyle } from 'react-native';

// Values from SweatScore_prototype-6.html. Unspecified CSS line heights remain
// native font metrics; do not manufacture a fixed line height for those roles.
export const prototypeColors = {
  ink: '#2a2a2a',
  muted: '#6f6f6f',
  subtle: '#8a8a8a',
  accent: '#ff5a1f',
  icon: '#e8541e',
  selected: '#fff3ea',
  border: '#ececec',
  secondary: '#f5f5f5',
  error: '#d92d20',
};
const families = {
  regular: 'Inter_400Regular',
  medium: 'Inter_500Medium',
  semibold: 'Inter_600SemiBold',
  bold: 'Inter_700Bold',
} as const;
function role(
  weight: keyof typeof families,
  size: number,
  lineHeight?: number,
  color = prototypeColors.ink,
  textAlign: TextStyle['textAlign'] = 'left'
): TextStyle {
  return {
    fontFamily: families[weight],
    fontWeight: 'normal',
    fontSize: size,
    ...(lineHeight === undefined ? {} : { lineHeight }),
    color,
    textAlign,
  };
}
export const prototypeTypography = StyleSheet.create({
  welcomeTitle: { ...role('bold', 28, 34, '#fff', 'center'), letterSpacing: -0.28 },
  todayTitle: { ...role('bold', 24, 30), letterSpacing: -0.24 },
  onboardingHeading: { ...role('bold', 22, 28), letterSpacing: -0.22 },
  dailyQuestionHeading: { ...role('bold', 26, 32), letterSpacing: -0.26 },
  planHeading: { ...role('bold', 28, 34), letterSpacing: -0.28 },
  challengeHeading: role('semibold', 17, 24, prototypeColors.ink, 'center'),
  challengeProgress: role('regular', 15, undefined, prototypeColors.muted),
  challengeProgressValue: role('semibold', 15),
  profileWeight: role('regular', 18),
  compactPageHeading: role('bold', 20, 26, prototypeColors.ink, 'center'),
  checkInSheetHeading: { ...role('bold', 26, 32), letterSpacing: -0.26 },
  celebrationHeading: {
    ...role('bold', 26, 32, prototypeColors.ink, 'center'),
    letterSpacing: -0.26,
  },
  otp: role('bold', 28, undefined, prototypeColors.ink, 'center'),
  badge: role('bold', 12),
  unit: role('medium', 15, undefined, prototypeColors.subtle, 'center'),
  selectedUnit: role('semibold', 15, undefined, prototypeColors.ink, 'center'),
  activityMetric: role('semibold', 26, 30, '#fff', 'center'),
  weekday: role('semibold', 12, undefined, prototypeColors.subtle, 'center'),
  currentWeekday: role('bold', 12, undefined, prototypeColors.ink, 'center'),
  photoTab: role('regular', 15, 20),
  compactAction: role('medium', 14),
  sectionHeading: role('semibold', 20, 24),
  sheetSectionHeading: role('semibold', 18, 24),
  cardTitle: role('semibold', 16, 22),
  compactCardTitle: role('semibold', 15, 20),
  body: role('regular', 15, 22, prototypeColors.muted),
  loadingBody: role('regular', 16, 24, prototypeColors.muted),
  explanation: role('regular', 15, 24, prototypeColors.muted),
  supporting: role('regular', 14, 20, prototypeColors.muted),
  caption: role('regular', 13, 18, prototypeColors.muted),
  smallCaption: role('regular', 12, 16, prototypeColors.muted),
  feedbackCaption: role('regular', 13, 20, prototypeColors.subtle),
  feedbackQuestion: role('medium', 16),
  label: role('semibold', 15, 20),
  field: role('regular', 16),
  option: role('regular', 16, 22),
  selectedOption: role('semibold', 16, 22),
  button: role('semibold', 17, undefined, '#fff', 'center'),
  bannerButton: role('bold', 15, undefined, prototypeColors.ink, 'center'),
  search: role('regular', 15),
  progressLabel: role('regular', 14, undefined, prototypeColors.muted),
  progressValue: role('semibold', 14),
  error: role('regular', 13, 18, prototypeColors.error),
});
export const prototypeComponents = StyleSheet.create({
  button: {
    minHeight: 56,
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  field: {
    minHeight: 56,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: prototypeColors.border,
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: '#fff',
  },
  option: {
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 22,
    borderWidth: 1.5,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  iconTile: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: prototypeColors.selected,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingIcon: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: prototypeColors.selected,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
